### ISSUE TITLE
Pagina descrittiva

### ISSUE THREAD

**Issue by Steffo99** [RYGhub/ld50#19]

**Comment by Cookie-CHR** [comment]
One cold night in late november, the brave and hipster lumberjack Reddy Summerson went outdoor to try his new fancy hoverboard. He traveled for a while, ignoring the cold sting, when suddently an army of evil snowmen appears on the horizon. They are the wicked army of Sanaklose, Lord of the Frost, Bringer of the Winter, here to conquer the land!

Reddy is isolated in the middle of the plains, far away from any tangible help, but he is not to be discouraged. With quick thinking, he makes a fireplace and, armed with his trusty crossbow, turns to face the icy enemies. But he better watch out, he better not cry, he better not pout and I'm telling you why: if Sanaklose's army is here, the Lord of the Frost itself will probably arrive soon...
